name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config
          # Install Apache Arrow from official repository
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://packages.apache.org/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          # Install only required Arrow packages for our use case
          sudo apt install -y -V libarrow-dev
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'macos'
        run: |
          xcode-select --install || true
          brew install apache-arrow
      - name: Install dependencies
        run: shards install
      - name: Build static library
        run: make all
      - name: Build executable
        run: make test
      - name: Run tests
        run: crystal spec
      - name: Run executable (help)
        run: ./kc --help
      - name: Run Linux Build
        if: matrix.os == 'ubuntu'
        run: |
          mkdir -p bin
          chmod 755 bin
          docker run -d --name alpine -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine apk add build-base readline-dev readline-static ncurses-dev ncurses-static ncurses-libs apache-arrow-dev pkgconfig
          docker exec alpine shards install --without-development --release
          docker exec alpine make clean
          docker exec alpine make all
          # Build with correct path for Alpine container
          docker exec alpine crystal build src/kc.cr -Dpreview_mt -Dexecution_context --link-flags="/workspace/libarrow_sparse.a -larrow" -o kc
          docker exec alpine chmod +x kc
          docker exec alpine cp kc bin/kc
          docker exec alpine gzip bin/kc
          docker exec alpine mv bin/kc.gz bin/kc-linux.gz
      - uses: actions/upload-artifact@v4
        with:
          name: kc-${{ matrix.os }}
          path: kc
