name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.arrow_impl }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
        arrow_impl: ["cpp", "crystal"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'ubuntu' && matrix.arrow_impl == 'cpp'
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config
          # Install Apache Arrow from official repository
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://packages.apache.org/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          # Install only required Arrow packages for our use case
          sudo apt install -y -V libarrow-dev
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'macos' && matrix.arrow_impl == 'cpp'
        run: |
          xcode-select --install || true
          brew install apache-arrow
      - name: Install basic build tools (Crystal implementation)
        if: matrix.arrow_impl == 'crystal'
        run: |
          if [ "${{ matrix.os }}" = "ubuntu" ]; then
            sudo apt update
            sudo apt install -y build-essential
          fi
      - name: Install dependencies
        run: shards install
      - name: Build with C++ implementation
        if: matrix.arrow_impl == 'cpp'
        run: make ARROW_IMPL=cpp
      - name: Build with Crystal implementation
        if: matrix.arrow_impl == 'crystal'
        run: make ARROW_IMPL=crystal
      - name: Run tests (C++ implementation)
        if: matrix.arrow_impl == 'cpp'
        run: crystal spec -Dpreview_mt -Dexecution_context -Dcpp_arrow
      - name: Run tests (Crystal implementation)
        if: matrix.arrow_impl == 'crystal'
        run: crystal spec -Dpreview_mt -Dexecution_context -Dcustom_binary
      - name: Run executable (help)
        run: ./kc --help
      - uses: actions/upload-artifact@v4
        with:
          name: kc-${{ matrix.os }}-${{ matrix.arrow_impl }}
          path: kc
