name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'ubuntu'
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config
          # Install Apache Arrow from official repository
          sudo apt install -y -V ca-certificates lsb-release wget
          wget https://packages.apache.org/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
          sudo apt update
          # Install only required Arrow packages for our use case
          sudo apt install -y -V libarrow-dev
      - name: Install C++ compiler and Arrow
        if: matrix.os == 'macos'
        run: |
          xcode-select --install || true
          brew install apache-arrow
      - name: Install dependencies
        run: shards install
      - name: Build static library
        run: make all
      - name: Build executable
        run: make test
      - name: Run tests
        run: crystal spec
      - name: Run executable (help)
        run: ./kc --help
      - uses: actions/upload-artifact@v4
        with:
          name: kc-${{ matrix.os }}
          path: kc
