name: build

on:
  push:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install C++ compiler
        if: matrix.os == 'ubuntu'
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Install C++ compiler
        if: matrix.os == 'macos'
        run: xcode-select --install || true
      - name: Install dependencies
        run: shards install
      - name: Build static library
        run: make all
      - name: Build executable
        run: make test
      - name: Run tests
        run: crystal spec
      - name: Run executable (help)
        run: ./kc --help
      - uses: actions/upload-artifact@v4
        with:
          name: kc-${{ matrix.os }}
          path: ${{ matrix.os == 'windows' && 'kc.exe' || 'kc' }}
