name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: Build Release ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Run Linux Build
        if: matrix.os == 'ubuntu'
        run: |
          mkdir -p bin
          chmod 755 bin
          docker run -d --name alpine -v $(pwd):/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine apk add readline-dev readline-static ncurses-dev ncurses-static ncurses-libs
          docker exec alpine shards install --without-development --release
          docker exec alpine shards build --release --static -Dpreview_mt -Dexecution_context
          docker exec alpine chmod +x bin/kc
          docker exec alpine gzip bin/kc
          docker exec alpine mv bin/kc.gz bin/kc-linux.gz

      - name: Run Mac Build x64
        if: matrix.os == 'macos'
        run: |
          shards install --without-development --release
          shards build --release -Dpreview_mt -Dexecution_context
          chmod +x bin/kc
          otool -L bin/kc
          gzip bin/kc
          mv bin/kc.gz bin/kc-macos.gz

      - name: Run Windows Build x64
        if: matrix.os == 'windows'
        run: |
          shards install --without-development --release
          shards build --release --static -Dpreview_mt -Dexecution_context
          Set-ExecutionPolicy RemoteSigned -Scope Process
          Compress-Archive -Path bin/kc.exe -DestinationPath bin/kc-windows.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/kc-linux.gz
            bin/kc-macos.gz
            bin/kc-windows.zip
            LICENSE
